theme = "bogster"

[keys.normal]
";" = "command_mode"     # ; opens command prompt (your request)
":" = "repeat_last_motion" # : repeats last motion/search (original ; function)
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["move_line_down", "goto_first_nonwhitespace"]
0   = "goto_line_start"
# Define 'Z' once, and list its sequences inside.
Z = { Z = ":wq", Q = ":q!" }
"C-r" = ":config-reload"
# C-y = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker-z.sh open"

[keys.normal.C-y]
z = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker-z.sh open"
t = ":sh tmux new-window -n fx '~/.config/helix/yazi-picker-tmux.sh open'"

[editor]
line-number = "relative"
color-modes = true
mouse = false
smart-tab.enable = false
# auto-pairs = false

# Resolve true color detection problems (e.g. on Linux in Windows WSL2)
# such as the error, "theme: theme requires true color support".
true-color = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]


[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
0   = "goto_line_start"

